# Codecov configuration for PJS
# Coverage requirements aligned with CLAUDE.md

coverage:
  status:
    project:
      default:
        target: 70%        # Overall project minimum
        threshold: 2%      # Allow 2% drop
    patch:
      default:
        target: 75%        # New code should be well-tested

  # Layer-specific coverage requirements
  precision: 2
  round: down
  range: "60...100"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

# Ignore test files and examples from coverage
ignore:
  - "tests/"
  - "benches/"
  - "examples/"
  - "crates/pjs-demo/"
  - "crates/pjs-bench/"
  - "**/tests.rs"
  - "**/test_*.rs"

# File-level coverage flags
flags:
  unittests:
    paths:
      - "crates/pjs-core/src/"
    carryforward: true

# Critical modules requiring high coverage
component_management:
  individual_components:
    # Domain layer - 80% minimum
    - component_id: domain
      paths:
        - "crates/pjs-core/src/domain/**"
      target: 80%
    
    # Security modules - 100% required
    - component_id: security
      paths:
        - "crates/pjs-core/src/security/**"
        - "crates/pjs-core/src/domain/services/validation_service.rs"
      target: 100%
    
    # Application layer - 70% minimum
    - component_id: application
      paths:
        - "crates/pjs-core/src/application/**"
      target: 70%
    
    # Infrastructure - 60% minimum
    - component_id: infrastructure
      paths:
        - "crates/pjs-core/src/infrastructure/**"
      target: 60%
