name: Bug Report
description: Report a bug in PJS (Protocol for JSON Streaming Protocol)
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: input
    id: version
    attributes:
      label: SJSP Version
      description: What version of SJSP are you using?
      placeholder: "e.g., 0.3.0"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - pjs-core (Core library)
        - pjs-js-client (JavaScript client)
        - pjs-demo (Demo applications)
        - pjs-bench (Benchmarking)
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: "Describe what happened and what you expected to happen"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. Create a stream with...
        2. Send data...
        3. Observe error...
      value: |
        1. 
        2. 
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: "Describe the expected behavior"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Describe what actually happened"
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Minimal code sample that reproduces the issue
      render: rust
      placeholder: |
        ```rust
        // Your minimal reproduction code here
        ```

  - type: textarea
    id: logs
    attributes:
      label: Error Logs/Output
      description: Any error messages, stack traces, or relevant output
      render: shell
      placeholder: "Paste any relevant logs or error messages here"

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: "e.g., Ubuntu 22.04, macOS 14.0, Windows 11"
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust Version
      description: What version of Rust are you using?
      placeholder: "e.g., 1.75.0"
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System crash, data loss)
        - High (Major functionality broken)
        - Medium (Minor functionality affected)
        - Low (Cosmetic or enhancement)
    validations:
      required: true

  - type: checkboxes
    id: performance
    attributes:
      label: Performance Impact
      description: Does this bug affect performance?
      options:
        - label: This bug causes significant performance degradation
        - label: This bug affects memory usage
        - label: This bug affects network efficiency
        - label: This bug affects parsing speed

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information that might be helpful
      placeholder: "Add any other context about the problem here"

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided a minimal reproduction case
          required: true
        - label: I am willing to help test a fix for this issue
          required: false
